"""phase 4: resumes, job descriptions, interview session details, question turns

Revision ID: 14907d01d4fe
Revises: 0908c1a6b5a3
Create Date: 2026-07-19 05:12:39.744535
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "14907d01d4fe"
down_revision: str | None = "0908c1a6b5a3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "job_descriptions",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("raw_text", sa.String(), nullable=False),
        sa.Column("structured_json", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "resumes",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("filename", sa.String(), nullable=True),
        sa.Column("full_text", sa.String(), nullable=False),
        sa.Column("structured_json", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "interview_session_details",
        sa.Column("session_id", sa.String(), nullable=False),
        sa.Column("resume_id", sa.String(), nullable=True),
        sa.Column("jd_id", sa.String(), nullable=True),
        sa.Column("config_json", sa.String(), nullable=False),
        sa.Column("plan_json", sa.String(), nullable=True),
        sa.Column("persona_id", sa.String(), nullable=False),
        sa.Column("session_mode", sa.String(), nullable=False),
        sa.Column("company_format", sa.String(), nullable=True),
        sa.Column("state", sa.String(), nullable=False),
        sa.Column("current_section_index", sa.Integer(), nullable=False),
        sa.Column("current_question_index", sa.Integer(), nullable=False),
        sa.Column("warm_up_stage", sa.String(), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("ended_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["jd_id"],
            ["job_descriptions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["resume_id"],
            ["resumes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
        ),
        sa.PrimaryKeyConstraint("session_id"),
    )
    op.create_table(
        "question_turns",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("session_id", sa.String(), nullable=False),
        sa.Column("question_id", sa.String(), nullable=False),
        sa.Column("question_text", sa.String(), nullable=False),
        sa.Column("is_follow_up", sa.Boolean(), nullable=False),
        sa.Column("answer_text", sa.String(), nullable=True),
        sa.Column("evaluation_json", sa.String(), nullable=True),
        sa.Column("asked_at", sa.DateTime(), nullable=False),
        sa.Column("answered_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("question_turns")
    op.drop_table("interview_session_details")
    op.drop_table("resumes")
    op.drop_table("job_descriptions")
    # ### end Alembic commands ###
