"""phase 5: confidence frames

Revision ID: af3625856fba
Revises: 14907d01d4fe
Create Date: 2026-07-19 21:16:46.425823
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "af3625856fba"
down_revision: str | None = "14907d01d4fe"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "confidence_frames",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("session_id", sa.String(), nullable=False),
        sa.Column("timestamp_ms", sa.Integer(), nullable=False),
        sa.Column("eye_contact_json", sa.String(), nullable=False),
        sa.Column("head_stability_json", sa.String(), nullable=False),
        sa.Column("blink_json", sa.String(), nullable=False),
        sa.Column("gesture_json", sa.String(), nullable=True),
        sa.Column("expression", sa.String(), nullable=False),
        sa.Column("composite_score", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_confidence_frames_session_id", "confidence_frames", ["session_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_confidence_frames_session_id", table_name="confidence_frames")
    op.drop_table("confidence_frames")
    # ### end Alembic commands ###
